name: lidar
channels:
  - pytorch
  - nvidia/label/cuda-12.4.1
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - cuda
  - cuda-toolkit
  - cuda-cudart
  - cuda-cupti
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-nvvm-tools=12.4
  - cuda-runtime=12.4
  - cuda-version
  - conda-forge::cudnn
  - gcc=12
  - gxx=12
  - pytorch-gpu=2.5.1
  - torchvision
  - torchaudio
  - ninja
  - google-sparsehash
  - h5py
  - pyyaml
  - tensorboard
  - tensorboardx
  - wandb
  - yapf
  - addict
  - einops
  - scipy
  - plyfile
  - termcolor
  - timm
  - ftfy
  - regex
  - tqdm
  - matplotlib
  - black
  - open3d
  - pip:
    - --find-links https://data.pyg.org/whl/torch-2.5.0+cu124.html
    - torch-cluster
    - torch-scatter
    - torch-sparse
    - torch-geometric
    - spconv-cu124
    - opencv-python
    - pyransac3d
    - yacs
    - scikit-image
    - joblib
    - chumpy
    - git+https://github.com/octree-nn/ocnn-pytorch.git
    - git+https://github.com/openai/CLIP.git
    - git+https://github.com/Dao-AILab/flash-attention.git
    - ./libs/pointops
    - ./libs/pointgroup_ops