DEVICE: 'cuda'
TRAIN:
  GEN:
    LR: 0.0001
    WD: 0.0001
    factor: 0.9
    patience: 1
    threshold: 0.01
    min_lr: 0.00000003
    metrics: 'train.mean_loss_param'
  with_body_label: False
  segment_parallel: False
  CosineAnnealingWarmRestarts: False
  use_drop_first: True
  use_denoice: False
  use_replace_noice: False
  no_denoice: False
  replace_noice_pc_rate: 0.2

MODEL:
  TpointNet2: False
  Outline: True
  Outline_boundary: False
  add_background: False
  add_twise_noise: False
  use_project_image: False
  use_back_wang: False
  use_transformer: False
  use_attention: False
  use_mdmtransformer: True

Transformer:
  num_hidden_layers: 3
  hidden_size: 1024
  num_attention_heads: 2
  intermediate_size: 512
  hidden_dropout_prob: 0.1
  
MDMTransformer:
  latent_dim: 1536
  dropout: 0.1
  num_heads: 4
  ff_size: 1024
  activation: 'gelu'
  num_layers: 8
  data_rep: 'rot6d'
  njoints: 24
  nfeats: 3
  seqlen: 16
  
LOSS:
  chamfer_loss: False
  nn_loss: False
  flow_loss: False
  end_loss: False
  pose_loss: True
  zmp_loss: False
  bone_loss: False

TrainDataset:
  dataset_path: 'your_data_path'
  use_aug: False
  use_rot: False
  concat_info: False
  use_straight: False
  use_pc_w_raw_z: False
  ret_raw_pc: True
  seqlen: 16
  drop_first_n: 0
  use_trans_to_normalize: False
  replace_noice_pc: False
  replace_noice_pc_rate: False
  replace_pc_strategy: 'random'
  noise_distribution: 'uniform'
  add_noice_pc: False
  set_body_label_all_one: False
  random_permutation: False
  use_boundary: False
  inside_random: False
  use_sample: False
  range_image: False
  range_image_W: 512
  range_image_H: 512
  fov_up: 12.5
  
  dataset_ids:
    - 20220707_A_174cm68kg18age_M_A002_A002_label_A001_A001_label
    - 20220708_B_158cm57kg20age_F_B004_B004_label_B005_B005_label_B002_B002_label_B003_B003_label
    - 20220708_B_158cm57kg20age_F_B004_B004_label_B005_B005_label_B002_B002_label
    - 20220708_B_158cm57kg20age_F_B004_B004_label_B005_B005_label
    - 20220708_B_158cm57kg20age_F_B004_B004_label
    - 20220708_C_165cm56kg16age_M_C002_C002_label
    - 20220711_D_155cm44kg13ageF_D002_D002_label_D001_D001_label_D004_D004_label_D005_D005_label_D003_D003_label_D006_D006_label
    - 20220711_D_155cm44kg13ageF_D002_D002_label_D001_D001_label_D004_D004_label_D005_D005_label
    - 20220711_D_155cm44kg13ageF_D002_D002_label_D001_D001_label
    - 20220711_D_155cm44kg13ageF_D002_D002_label
    - 20220711_F_171cm57kg20age_F_F002_F002_label
    - 20220712_A_174cm68kg18age_M_A001_A001_label
    - 20220712_G_175cm65kg18age_M_G001_G001_label
    - 20220712_H_156cm16age_F_H003_H003_label_H002_H002_label
    - 20220712_H_156cm16age_F_H003_H003_label
    - 20220713_E_177cm68kg16age_M_E002_E002_label_E003_E003_label
    - 20220713_E_177cm68kg16age_M_E002_E002_label
    - 20220714_B_158cm57kg20age_F_B002_B002_label_B001_B002
    - 20220714_B_158cm57kg20age_F_B002_B002_label
    - 20220714_D_155cm44kg13age_F_D002_D002_label_D001_D001_label
    - 20220714_D_155cm44kg13age_F_D002_D002_label
    - cimi4d_XMU_0930_001_V1
    - cimi4d_XMU_0930_002_V1
    - cimi4d_XMU_0930_003_V1
    - cimi4d_XMU_0930_006_V1
    - cimi4d_XMU_0930_007_V1
    - cimi4d_XMU_0930_009_V1
    - cimi4d_XMU_1023_ym001_V1_0
    - cimi4d_XMU_1023_ym002_V1
    - cimi4d_XMU_1023_zpc004_V1_0

# '/SAMSUMG8T/mqh/lidarcapv2/dataset'
# '/SAMSUMG8T/zjy/outlier'
TestDataset:
  dataset_path: "your_data_path"
  use_aug: False
  concat_info: False
  use_rot: False
  use_straight: False
  use_pc_w_raw_z: False
  ret_raw_pc: True
  seqlen: 16
  drop_first_n: 0
  use_trans_to_normalize: False
  replace_pc_strategy: 'random'
  replace_noice_pc: False
  replace_noice_pc_rate: False
  noise_distribution: 'uniform'
  add_noice_pc: False
  set_body_label_all_one: False
  random_permutation: False
  use_boundary: False
  inside_random: False
  use_sample: False
  range_image: False
  range_image_W: 512
  range_image_H: 512
  fov_up: 12.5
  
  dataset_ids:
    - 20220707_A_174cm68kg18age_M_A002_A002_label
    - 20220709_D_155cm44kg13age_F_D002_D002_label
    - 20220711_D_155cm44kg13ageF_D002_D002_label_D001_D001_label_D004_D004_label_D005_D005_label_D003_D003_label
    - 20220711_D_155cm44kg13ageF_D002_D002_label_D001_D001_label_D004_D004_label
    - 20220711_F_171cm57kg20age_F_F002_F002_label_F003_F003_label
    - 20220714_B_158cm57kg20age_F_B002_B002_label_B001_B002_B003_B003_label
    - cimi4d_XMU_1023_wjy002_V1
    - cimi4d_XMU_1023_zpc001_V1_2
    - cimi4d_XMU_1023_zpc006_V1_0
