DEVICE: 'cuda'
TRAIN:
  GEN:
    LR: 0.0001
    WD: 0.0001
    factor: 0.9
    patience: 1
    threshold: 0.01
    min_lr: 0.00000003
    metrics: 'train.mean_loss_param'
  with_body_label: False
  segment_parallel: False
  CosineAnnealingWarmRestarts: False
  use_drop_first: True
  use_denoice: False
  use_replace_noice: False
  no_denoice: False
  replace_noice_pc_rate: 0.2

MODEL:
  TpointNet2: False
  Outline: True
  Outline_boundary: True
  use_background: False

LOSS:
  chamfer_loss: False
  nn_loss: False
  flow_loss: False
  end_loss: False
  pose_loss: True

TrainDataset:
  dataset_path: 'your_data_path'
  use_aug: False
  use_rot: False
  use_straight: False
  use_pc_w_raw_z: False
  ret_raw_pc: True
  seqlen: 16
  drop_first_n: 0
  use_trans_to_normalize: True
  replace_noice_pc: False
  replace_noice_pc_rate: False
  replace_pc_strategy: 'random'
  noise_distribution: 'uniform'
  add_noice_pc: False
  set_body_label_all_one: False
  random_permutation: False
  use_boundary: False
  inside_random: False
  use_sample: True

  dataset_ids:
    - 51801
    - 51802
    - 51803
    - 51808
    - 51807
    - 61102
    - 61103
    - 61105
    - 61108
    - 61109
    - 61201
    - 61202
    - 61203
    - 61206
    - 61207
    - 61210
    - 61212
    - 61213
    - 61301
    - 61302
    - 61304
    - 61305
    - 61306
    - 61307
    - 61704
    - 61705
    - 61706
    - 61707
    - 61708
    - 61709
    - 61711
    - 61714
    - 61801
    - 61802
    - 61803
    - 61804
    - 61805
    - 61808
    - 51809
    - 51804
    - 51812
    - 51810

TestDataset:
  dataset_path: 'your_data_path'
  use_aug: False
  use_rot: False
  use_straight: False
  use_pc_w_raw_z: False
  ret_raw_pc: True
  seqlen: 16
  drop_first_n: 0
  use_trans_to_normalize: True
  replace_pc_strategy: 'random'
  replace_noice_pc: False
  replace_noice_pc_rate: False
  noise_distribution: 'uniform'
  add_noice_pc: False
  set_body_label_all_one: False
  random_permutation: False
  use_boundary: False
  inside_random: False
  add_boundary: True
  use_sample: False

  dataset_ids:
    - 1004_lyy_musicsquare2_1711_1754
    - 1004_lyy_musicsquare2_1765_6909
    - 1004_lyy_musicsquare2_187_347
    - 1004_lyy_musicsquare2_385_654
    - 1004_lyy_musicsquare2_721_1698
    - 1004_sw_zhongshan2_1303_6622
    - 1004_sw_zhongshan2_193_1292
    - 1009_lzh_szgarden1_154_2552
